on:
  push:
    tags:
      - 'v*'

name: Publish on Push

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            artifact_name: nxssetup
            asset_name: linux.x86_64
          - os: windows-latest
            artifact_name: nxssetup.exe
            asset_name: windows.exe
          - os: macos-latest
            artifact_name: nxssetup
            asset_name: mac

    steps:
    - name: Get Version from Tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - uses: actions/checkout@v1
      name: Checkout Master
      
    - uses: actions-rs/toolchain@v1
      name: Install latest nightly
      with:
        toolchain: nightly
        default: true

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: nxssetup-${{ steps.get_version.outputs.VERSION }}-${{ matrix.asset_name }}
        tag: ${{ github.ref }}